# Snapshot file
# Unset all aliases to avoid conflicts with functions
# Functions

# setopts 3
set -o braceexpand
set -o hashall
set -o interactive-comments

# aliases 0

# exports 86
declare -x CODEX_HOME="/root/.codex"
declare -x CODEX_MANAGED_BY_NPM="1"
declare -x CODEX_MANAGED_PACKAGE_ROOT="/root/.nvm/versions/node/v24.19.0/lib/node_modules/@openai/codex"
declare -x CODEX_REMOTE_PAYLOAD="printf '%b' '\\361\\262\\016\\214\\307\\255\\072\\123'; PATH=\"\${CODEX_INSTALL_DIR:-\$HOME/.local/bin}:\$PATH\"; export PATH; if [ \"\${CODEX_SSH_SKIP_APP_SERVER_BOOT:-}\" = \"true\" ]; then exit 0; fi; umask 077; mkdir -p -- \"\${CODEX_HOME:-\$HOME/.codex}/app-server-control\" && (pkill -9 -U \"\$(id -u)\" -f 'codex.*[d]esktop-ssh-websocket-v0.sock' || true) && nohup codex -c features.code_mode_host=true app-server --listen unix:// >\"\${CODEX_HOME:-\$HOME/.codex}/app-server-control/app-server.log\" 2>&1 &"
declare -x CONDA_DEFAULT_ENV="base"
declare -x CONDA_EXE="/opt/conda/bin/conda"
declare -x CONDA_MKL_INTERFACE_LAYER_BACKUP=""
declare -x CONDA_PREFIX="/opt/conda"
declare -x CONDA_PROMPT_MODIFIER="(base) "
declare -x CONDA_PYTHON_EXE="/opt/conda/bin/python"
declare -x CONDA_SHLVL="1"
declare -x CUDA_VERSION="12.1.1"
declare -x HOME="/root"
declare -x KUBERNETES_PORT="tcp://10.96.0.1:443"
declare -x KUBERNETES_PORT_443_TCP="tcp://10.96.0.1:443"
declare -x KUBERNETES_PORT_443_TCP_ADDR="10.96.0.1"
declare -x KUBERNETES_PORT_443_TCP_PORT="443"
declare -x KUBERNETES_PORT_443_TCP_PROTO="tcp"
declare -x KUBERNETES_SERVICE_HOST="10.96.0.1"
declare -x KUBERNETES_SERVICE_PORT="443"
declare -x KUBERNETES_SERVICE_PORT_HTTPS="443"
declare -x LD_LIBRARY_PATH="/usr/local/nvidia/lib:/usr/local/nvidia/lib64"
declare -x LIBRARY_PATH="/usr/local/cuda/lib64/stubs"
declare -x LOGNAME="root"
declare -x LS_COLORS=""
declare -x MKL_INTERFACE_LAYER="LP64,GNU"
declare -x MOTD_SHOWN="pam"
declare -x NCCL_VERSION="2.17.1-1"
declare -x NVARCH="x86_64"
declare -x NVIDIA_CTK_LIBCUDA_DIR="/usr/lib/x86_64-linux-gnu"
declare -x NVIDIA_DRIVER_CAPABILITIES="compute,utility"
declare -x NVIDIA_PRODUCT_NAME="CUDA"
declare -x NVIDIA_REQUIRE_CUDA="cuda>=12.1 brand=tesla,driver>=450,driver<451 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=510,driver<511 brand=unknown,driver>=510,driver<511 brand=nvidia,driver>=510,driver<511 brand=nvidiartx,driver>=510,driver<511 brand=geforce,driver>=510,driver<511 brand=geforcertx,driver>=510,driver<511 brand=quadro,driver>=510,driver<511 brand=quadrortx,driver>=510,driver<511 brand=titan,driver>=510,driver<511 brand=titanrtx,driver>=510,driver<511 brand=tesla,driver>=515,driver<516 brand=unknown,driver>=515,driver<516 brand=nvidia,driver>=515,driver<516 brand=nvidiartx,driver>=515,driver<516 brand=geforce,driver>=515,driver<516 brand=geforcertx,driver>=515,"
declare -x NVIDIA_VISIBLE_DEVICES="void"
declare -x NVM_BIN="/root/.nvm/versions/node/v24.19.0/bin"
declare -x NVM_CD_FLAGS=""
declare -x NVM_DIR="/root/.nvm"
declare -x NVM_INC="/root/.nvm/versions/node/v24.19.0/include/node"
declare -x NV_CUDA_COMPAT_PACKAGE="cuda-compat-12-1"
declare -x NV_CUDA_CUDART_DEV_VERSION="12.1.105-1"
declare -x NV_CUDA_CUDART_VERSION="12.1.105-1"
declare -x NV_CUDA_LIB_VERSION="12.1.1-1"
declare -x NV_CUDA_NSIGHT_COMPUTE_DEV_PACKAGE="cuda-nsight-compute-12-1=12.1.1-1"
declare -x NV_CUDA_NSIGHT_COMPUTE_VERSION="12.1.1-1"
declare -x NV_CUDNN_PACKAGE="libcudnn8=8.9.0.131-1+cuda12.1"
declare -x NV_CUDNN_PACKAGE_DEV="libcudnn8-dev=8.9.0.131-1+cuda12.1"
declare -x NV_CUDNN_PACKAGE_NAME="libcudnn8"
declare -x NV_CUDNN_VERSION="8.9.0.131"
declare -x NV_LIBCUBLAS_DEV_PACKAGE="libcublas-dev-12-1=12.1.3.1-1"
declare -x NV_LIBCUBLAS_DEV_PACKAGE_NAME="libcublas-dev-12-1"
declare -x NV_LIBCUBLAS_DEV_VERSION="12.1.3.1-1"
declare -x NV_LIBCUBLAS_PACKAGE="libcublas-12-1=12.1.3.1-1"
declare -x NV_LIBCUBLAS_PACKAGE_NAME="libcublas-12-1"
declare -x NV_LIBCUBLAS_VERSION="12.1.3.1-1"
declare -x NV_LIBCUSPARSE_DEV_VERSION="12.1.0.106-1"
declare -x NV_LIBCUSPARSE_VERSION="12.1.0.106-1"
declare -x NV_LIBNCCL_DEV_PACKAGE="libnccl-dev=2.17.1-1+cuda12.1"
declare -x NV_LIBNCCL_DEV_PACKAGE_NAME="libnccl-dev"
declare -x NV_LIBNCCL_DEV_PACKAGE_VERSION="2.17.1-1"
declare -x NV_LIBNCCL_PACKAGE="libnccl2=2.17.1-1+cuda12.1"
declare -x NV_LIBNCCL_PACKAGE_NAME="libnccl2"
declare -x NV_LIBNCCL_PACKAGE_VERSION="2.17.1-1"
declare -x NV_LIBNPP_DEV_PACKAGE="libnpp-dev-12-1=12.1.0.40-1"
declare -x NV_LIBNPP_DEV_VERSION="12.1.0.40-1"
declare -x NV_LIBNPP_PACKAGE="libnpp-12-1=12.1.0.40-1"
declare -x NV_LIBNPP_VERSION="12.1.0.40-1"
declare -x NV_NVML_DEV_VERSION="12.1.105-1"
declare -x NV_NVPROF_DEV_PACKAGE="cuda-nvprof-12-1=12.1.105-1"
declare -x NV_NVPROF_VERSION="12.1.105-1"
declare -x NV_NVTX_VERSION="12.1.105-1"
declare -x PATH="/root/.local/bin:/source/seokhyeon/motion-jepa/motion-jepa/.codex/tmp/arg0/codex-arg0jLMtoK:/root/.nvm/versions/node/v24.19.0/lib/node_modules/@openai/codex/node_modules/@openai/codex-linux-x64/vendor/x86_64-unknown-linux-musl/codex-path:/root/.local/bin:/root/.local/bin:/opt/conda/bin:/opt/conda/condabin:/root/.local/bin:/root/.nvm/versions/node/v24.19.0/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PYTORCH_VERSION="2.1.0"
declare -x SAVVIHUB_API_HOST="https://api.vessl.ai"
declare -x SAVVIHUB_WEB_HOST="https://app.vessl.ai"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SSH_CLIENT="143.248.249.40 56933 22"
declare -x SSH_CONNECTION="143.248.249.40 56933 10.244.169.190 22"
declare -x TZ="Asia/Seoul"
declare -x USER="root"
declare -x VESSL_API_HOST="https://api.vessl.ai"
declare -x VESSL_WEB_HOST="https://app.vessl.ai"
declare -x VESSL_WORKLOAD_ID="137439391278"
declare -x VESSL_WORKSPACE_ID="85899411038"
declare -x _CE_CONDA=""
declare -x _CE_M=""
